name: Testing and Release
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  bash-n:
    name: Bash N
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Running bash -n
        run: |
          find . -name '*.sh' -exec bash -n {} \;

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env: 
          SHELLCHECK_OPTS: "-x"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Unit Tests
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          failed_tests=0
          for f in tests/*.sh; do
            echo "Running $f"
            if ! bash -e "$f"; then
              echo "FAILED: $f"
              failed_tests=$((failed_tests + 1))
            else
              echo "PASSED: $f"
            fi
          done
          if [[ $failed_tests -gt 0 ]]; then
            echo "$failed_tests test(s) failed"
            exit 1
          else
            echo "All tests passed!"
          fi


  semver:
    name: Auto Tag (main)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [bash-n, shellcheck, unit-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
